# Site settings
title: Keep Trackin'
email: rschuster3@gmail.com
description: "Documenting my experiences and others' stories as I come across them"
baseurl: "/keep_trackin"
url: "http://rschuster3.github.io/keep_trackin"
comments :
  provider : disqus
  disqus :
    short_name : keep-trackin

# Build settings
markdown: kramdown
permalink: pretty